# Generated by Django 4.2.5 on 2023-09-25 08:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Arts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upload',
            options={'ordering': ('name',), 'verbose_name_plural': 'Upload'},
        ),
        migrations.AddField(
            model_name='upload',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 9, 25, 8, 21, 6, 572365, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Upload', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='upload',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='image',
            field=models.ImageField(blank=True, upload_to='Upload_images'),
        ),
        migrations.AddField(
            model_name='upload',
            name='reason_of_rejection',
            field=models.TextField(blank=True),
        ),
    ]
