# Generated by Django 4.2.5 on 2023-09-25 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Arts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upload',
            options={'ordering': ('name',), 'verbose_name_plural': 'Upload'},
        ),
    ]
