# Generated by Django 4.2.5 on 2023-09-25 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Arts', '0002_alter_upload_options_upload_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Upload', to=settings.AUTH_USER_MODEL),
        ),
    ]
