# Generated by Django 4.2.5 on 2023-09-25 08:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Arts', '0003_alter_upload_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='upload',
            name='created_by',
            field=models.ForeignKey(default=datetime.datetime(2023, 9, 25, 8, 25, 18, 397614, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, related_name='Upload', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
