# Generated by Django 4.2.2 on 2023-09-28 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Arts', '0004_info_contact_info_title_info_reason_of_rejection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upload',
            options={'ordering': ('name',), 'verbose_name_plural': 'Uploads'},
        ),
        migrations.RenameField(
            model_name='info',
            old_name='imgae',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='info',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='info',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_info', to='Arts.upload'),
        ),
    ]
